version: '3.7'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'

  node-app:
    build: artifacts/gate-simulator
    image: latest
    ports:
      - '9999:9999'